apiVersion: v1
kind: Secret
metadata:
  name: promql-proxy-upstream-auth
  namespace: monitoring
  labels:
    app.kubernetes.io/name: promql-proxy
type: Opaque
stringData:
  username: promql-proxy
  password: promql-secret-pass
